version: '3.4'

networks:
  logaccentureapi:

services:
  app-db:
    container_name: app-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 8002:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Logs@2022
    networks:
      - logaccentureapi
  log.accenture.api:
    container_name: LogSystem
    image: ${DOCKER_REGISTRY-}logaccentureapi
    build:
      context: .
      dockerfile: Log.Accenture.Api/Dockerfile
    ports:
      - 8001:80
    depends_on:
      - app-db
    environment:
      - DB_HOST=app-db
      - DBNAME=TestAccenture
      - DB_SA_PASSWORD=Logs@2022
    networks:
      - logaccentureapi
  
  